# https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/pypi-tools/examples/cleartext-cloudbuild.yaml
substitutions:
  _VERSION: 0.1.0 # default value
steps:
  - name: 'us.gcr.io/$PROJECT_ID/python'
    args: ['cardano-py-pkg/setup.py', 'bdist_wheel', '--universal']

  - name: 'us.gcr.io/$PROJECT_ID/python'
    entrypoint: 'twine'
    args: ['check', 'dist/*']

  - name: 'us.gcr.io/$PROJECT_ID/python'
    entrypoint: 'twine'
    args: ['upload', 'dist/*', '-u', '__token__', '-p', '$$PYPI_API_KEY', '--verbose']
    secretEnv: [ 'PYPI_API_KEY' ]

availableSecrets:
  secretManager:
    - versionName: projects/cardano-etl/secrets/cardanopy-pypi-api-token/versions/1
      env: 'PYPI_API_KEY'