# https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/pypi-tools/examples/cleartext-cloudbuild.yaml
substitutions:
  _VERSION: 0.1.0 # default value
steps:
  - name: 'us.gcr.io/$PROJECT_ID/python'
    args: ['cardano-py-pkg/setup.py', 'bdist_wheel', '--universal']

  - name: 'us.gcr.io/$PROJECT_ID/python'
    entrypoint: 'twine'
    args: ['check', 'cardano-py-pkg/dist/*']

  - name: 'us.gcr.io/$PROJECT_ID/python'
    entrypoint: 'bash'
    args:
      - -c
      - |
        cd cardano-py-pkg && \
        code_version=$(python setup.py --version) && \
        pip_version=$(yolk -V kondunite | cut -d" " -f2) && \
        ([ "$code_version" != "$pip_version" ] && twine upload dist/* -u __token__ -p $$PYPI_API_KEY || echo "No new version")
    secretEnv: [ 'PYPI_API_KEY' ]

availableSecrets:
  secretManager:
    - versionName: projects/cardano-etl/secrets/cardanopy-pypi-api-token/versions/1
      env: 'PYPI_API_KEY'