substitutions:
  _VERSION: 1.25.1 # default value
  _CONTAINER: "cardano-py-slim"
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=chbfiv --password=$$DOCKER_API_KEY']
    secretEnv: ['DOCKER_API_KEY']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg', '_VERSION=$_VERSION',
           '--cache-from', 'floydcraft/$_CONTAINER:latest',
           '-t', 'floydcraft/$_CONTAINER:$COMMIT_SHA',
           '-t', 'floydcraft/$_CONTAINER:$_VERSION',
           '-t', 'floydcraft/$_CONTAINER:latest',
           '$_CONTAINER']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'push', 'floydcraft/$_CONTAINER']

availableSecrets:
  secretManager:
    - versionName: projects/cardano-etl/secrets/docker-chbfiv/versions/1
      env: 'DOCKER_API_KEY'