apiVersion: v1
kind: Service
metadata:
  name: cardano-node-lb
  namespace: {{ .Values.namespace | quote }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: cardano-node-deployment
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001