apiVersion: v1
kind: Service
metadata:
  name: producer-statefulset-lb
  namespace: {{ .Values.namespace | quote }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: producer-statefulset
    targetRole: {{ .Values.releaseRole | quote }}
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001