apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardano-node-pvc
  namespace: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi