apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: relay-statefulset
  labels:
    app: relay-statefulset
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: relay-statefulset-lb
  replicas: 2
  selector:
    matchLabels:
      app: relay-statefulset
  template:
    metadata:
      labels:
        app: relay-statefulset
    spec:
      containers:
        - name: relay-container
          image: {{ .Values.cardanoNode.image | quote }}
          command: ["cardanopy",
                    "run",
                    "--sub",
                    {{ printf "_POD_ORDINAL=%s" .Values.cardanoNode.podOrdirnal | quote }},
                    "--sub",
                    {{ printf "_TARGET_POD_ORDINAL=%s" .Values.cardanoNode.targetPodOrdirnal | quote }},
                    {{ .Values.appDir | quote }} ]
          env:
            - name: CARDANO_NETWORK
              value: {{ .Values.cardanoNode.network | quote }}
            - name: CARDANO_NODE_SOCKET_PATH
              value: {{ .Values.cardanoNode.socketPath | quote }}
          ports:
            - containerPort: 3001
            - containerPort: 12798
            - containerPort: 12788
          volumeMounts:
              - mountPath: {{ .Values.cardanoNode.appDir | quote  }}
                name: relay-pvc
      initContainers:
        - name: init-producer-container
          image: {{ .Values.cardanoNode.image | quote }}
          command: [ "cardanopy",
                     "create",
                     "--template",
                     "relay-k8s",
                     "--network",
                     {{ .Values.cardanoNode.network | quote  }},
                     {{ .Values.cardanoNode.appDir | quote }} ]
      nodeSelector:
        pool: default
  volumeClaimTemplates:
    - metadata:
        name: relay-pvc
        namespace: {{ .Values.namespace | quote }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
