apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: relay-statefulset
  labels:
    app: relay-statefulset
  namespace: {{ .Values.namespace | quote }}
spec:
  serviceName: relay-statefulset-lb
  replicas: 2
  selector:
    matchLabels:
      app: relay-statefulset
  template:
    metadata:
      labels:
        app: relay-statefulset
    spec:
      containers:
        - name: relay-container
          image: {{ .Values.cardanoImage }}
          args: ["run", "/app"]
          env:
            - name: CARDANO_NETWORK
              value: {{ .Values.cardano.network }}
            - name: CARDANO_NODE_SOCKET_PATH
              value: {{ printf "/storage/%s/node.socket" .Values.cardano.network | quote }}
          ports:
            - containerPort: 3001
            - containerPort: 12798
            - containerPort: 12788
          volumeMounts:
              - mountPath: /storage
                name: relay-pvc
      nodeSelector:
        pool: default
  volumeClaimTemplates:
    - metadata:
        name: relay-pvc
        namespace: {{ .Values.namespace | quote }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
