buildId: b7eacd01-a2bb-41d6-aec5-d160df5371af
version: 1.25.1
commitSha: 8b2aad2aeda7da173bcceed1fdf07ce6ae09cc91
branchName: master
cardanoImage: floydcraft/cardano-py-slim:8b2aad2aeda7da173bcceed1fdf07ce6ae09cc91