apiVersion: v1
nodes:
  producer-statefulset-0:
    config: "config.json"
    topology:
      Producers:
        - addr: "relays-new.cardano-testnet.iohkdev.io"
          port: 3001
          valency: 2
    databasePath: "/storage/db"
    hostAddr: "0.0.0.0"
    port: 3001
    socketPath: "/storage/node.socket"
  relay-statefulset-0:
    config: "config.json"
    topology:
      Producers:
        - addr: "producer-statefulset-0.producer-statefulset-lb.cardano-testnet.svc.cluster.local"
          port: 3001
          valency: 1
        - addr: "relay-statefulset-1.relay-statefulset-lb.cardano-testnet.svc.cluster.local"
          port: 3001
          valency: 1
        - addr: "relays-new.cardano-testnet.iohkdev.io"
          port: 3001
          valency: 2
    databasePath: "/storage/db"
    hostAddr: "0.0.0.0"
    port: 3001
    socketPath: "/storage/node.socket"
  relay-statefulset-1:
    config: "config.json"
    topology:
      Producers:
        - addr: "producer-statefulset-0.producer-statefulset-lb.cardano-testnet.svc.cluster.local"
          port: 3001
          valency: 1
        - addr: "relay-statefulset-0.relay-statefulset-lb.cardano-testnet.svc.cluster.local"
          port: 3001
          valency: 1
        - addr: "relays-new.cardano-testnet.iohkdev.io"
          port: 3001
          valency: 2
    databasePath: "/storage/db"
    hostAddr: "0.0.0.0"
    port: 3001
    socketPath: "/storage/node.socket"