nodes:
  relay-statefulset-0:
    config: "config.json"
    topology:
      Producers:
        - addr: "relays-new.cardano-testnet.iohkdev.io"
          port: 3001
          valency: 2
    databasePath: "/storage/db"
    hostAddr: "0.0.0.0"
    port: 3001
    socketPath: "/storage/node.socket"