substitutions:
  _VERSION: 1.25.1 # default value
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=chbfiv --password=$$DOCKER_API_KEY']
    secretEnv: ['DOCKER_API_KEY']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg', '_VERSION=$_VERSION',
           '--cache-from', 'floydcraft/cardano-node-iohk:latest',
           '-t', 'floydcraft/cardano-node-iohk:$COMMIT_SHA',
           '-t', 'floydcraft/cardano-node-iohk:$_VERSION',
           '-t', 'floydcraft/cardano-node-iohk:latest',
           'cardano-node-iohk']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'push', 'floydcraft/cardano-node-iohk']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
      - dir="cardano-node-iohk-slim"
        echo "Building $dir ... "
        logfile="$dir.log"
        failfile="$dir.fail"
        gcloud builds submit $dir --config=$dir/cloudbuild.xml > ${logfile} 2>&1
        if [[ $? -ne 0 ]]; then
          echo "$dir failed" | tee -a ${failfile}
          cat ${logfile}
        fi
        # Check if there is any failure.
        if [[ -s ${failfile} ]]; then
          echo
          echo "build failed:"
          cat ${logfile}
          echo "Exiting."
          exit 1
        fi
        echo "Build succeeded."

  - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
        - dir="cardano-node-slim"
          echo "Building $dir ... "
          logfile="$dir.log"
          failfile="$dir.fail"
          gcloud builds submit $dir --config=$dir/cloudbuild.xml > ${logfile} 2>&1
          if [[ $? -ne 0 ]]; then
          echo "$dir failed" | tee -a ${failfile}
          cat ${logfile}
          fi
          # Check if there is any failure.
          if [[ -s ${failfile} ]]; then
          echo
          echo "build failed:"
          cat ${logfile}
          echo "Exiting."
          exit 1
          fi
          echo "Build succeeded."

timeout: 8000s
options:
  machineType: 'N1_HIGHCPU_8'
availableSecrets:
  secretManager:
    - versionName: projects/cardano-etl/secrets/docker-chbfiv/versions/1
      env: 'DOCKER_API_KEY'



