substitutions:
  _VERSION: 1.25.1 # default value
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=chbfiv --password=$$DOCKER_API_KEY']
    secretEnv: ['DOCKER_API_KEY']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg', '_VERSION=$_VERSION',
           '--cache-from', 'floydcraft/cardano-node-iohk:latest',
           '-t', 'floydcraft/cardano-node-iohk:$COMMIT_SHA',
           '-t', 'floydcraft/cardano-node-iohk:$_VERSION',
           '-t', 'floydcraft/cardano-node-iohk:latest',
           'cardano-node-iohk']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'push', '--all-tags', 'floydcraft/cardano-node-iohk']
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args: ['-c' 'curl https://cloudbuild.googleapis.com/v1/projects/cardano-etl/triggers/cardano-node-iohk-slim-webhook:webhook?secret=$$CARDANO_ETL_WEBHOOK&key=$$CARDANO_ETL_API_KEY']
timeout: 3600s
options:
  machineType: 'N1_HIGHCPU_8'
availableSecrets:
  secretManager:
    - versionName: projects/cardano-etl/secrets/docker-chbfiv/versions/1
      env: 'DOCKER_API_KEY'
    - versionName: projects/cardano-etl/secrets/cardano-etl-api-key/versions/1
      env: 'CARDANO_ETL_API_KEY'
    - versionName: projects/cardano-etl/secrets/cardano-etl-webhook/versions/1
      env: 'CARDANO_ETL_WEBHOOK'



